.286
pila SEGMENT STACK
	DB 32 DUP ('STACK...')

pila ENDS


datos SEGMENT
	CAD1 DB  5 DUP(?),'$'
	CAD2 DB  5 DUP(?),'$'

	LETRERO1 DB 0AH,'ingresa cadena 1:', 0DH, 0AH, '$'
	LETRERO2 DB 0AH,'ingresa cadena 2:', 0DH, 0AH, '$'
	letre DB 0AH,'son iguales', 0DH, 0AH, '$'

	longitudcadena1 DW ('?'),'$'
datos ENDS

codigo SEGMENT 'CODE'
	ASSUME SS:pila, DS:datos, CS:codigo
	Main Proc FAR

	PUSH DS
	PUSH 0
	MOV AX, datos
	MOV DS, AX   ; HASTA AQUI ERA LO QUE HACIAMOS
	MOV ES, AX  ; GUADAMOS EN EL SEGMENTO EXTRA LOS DATOS , ESTE ES EL ENGAÑO REALMENTE NO LO ES POR QUE AL FINAL ESTAMOS OCUPANDO
	             ; OTRO SEGMENTO, ES MAS BIEN UNA MANIPULACION PERO CON ESO PODEMOS SOBREESCRIBIR DOS LOCALIDADES DE MEMORIA




							 				MOV AH,09H ; IMPRESION DE CAD1
							 		    LEA DX,LETRERO1
							 		    INT 21H


MOV SI,0

ciclo:
MOV AH,01H
INT 21H
CMP AL,13
JE salir
MOV CAD1[SI],AL
INC SI

CMP SI,5
JAE salir
JMP ciclo

salir:

mov longitudcadena1,SI


MOV AH,09H ; IMPRESION DE CAD1
LEA DX,LETRERO2
INT 21H



MOV SI,0

ciclo2:
MOV AH,01H
INT 21H
CMP AL,13
JE salir2
MOV CAD2[SI],AL
INC SI

CMP SI,5
JAE salir2
JMP ciclo2

salir2:


cmp longitudcadena1,SI
JNE final

		; ESTO ES COMO PONER MOV CAD2,CAD1
		MOV SI,OFFSET CAD2 ; SIEMPRE EL  SEGMENTO EXTRA  VA A ESTAR DADO POR EL REGISTRO DI
		MOV DI,OFFSET CAD1  ;SIEMPRE EL  SEGMENTO DE DATOS  VA A ESTAR DADO POR EL REGISTRO SI
		                    ; ALGO IMPORTANTE ES QUE EL MOV CAD2,CAD1 EN REALIDAD SOLO MUEVE UN CARACTER, POR ESO NECESITAMOS DE UN CICLO
		MOV CX,longitudcadena1    ; INICIALIZA EL REPEAT EN 5 SIEMPRE VA A SER EN ESTE REGISTRO

		REPE CMPSB   ; EL REPEAT FUNCIONA COMO EL LOOP SOLO QUE ES ESPECIAL PARA EL MOVS , LE PONEMOS LA B POR QUE LO DEFINIMOS ANTERIORMENTE COMO UN BYTE.
		            ; SI HUBIERAMOS DEFINIMO COMO PALABRA SERIA REP MOVSW
JNE final

MOV AH,09H ; IMPRESION DE CAD1
LEA DX,letre
INT 21H


			;MOV AH,09H ; IMPRESION DE CAD1
		   ; LEA DX,CAD1
		    ;INT 21H

				;MOV AH,09H ; IMPRESION DE CAD1
				;LEA DX,CAD2
				;INT 21H

final:
		RET
	Main ENDP
codigo ENDS
END Main
